### ISSUE TITLE
allow interoperability with pydantic

### ISSUE THREAD

**Issue by juancoquet** [juancoquet/sensible-types#1]
doesn't work with pydantic.

make it work with pydantic.

**Comment by jonah-ramponi-xapien** [comment]
<img width="1009" alt="Screenshot 2024-11-12 at 11 13 07" src="https://github.com/user-attachments/assets/bd3bd2ca-be86-4c1f-88ba-15fc7e9b3d53">

**Comment by juancoquet** [comment]
@jonah-ramponi-xapien now compatible with pydantic in version `0.2.0`: https://pypi.org/project/sensible-types/
